examples/advanced_stimuli.py, examples/analysis_demo.py, examples/basic_experiment.py, examples/drawing_methods.py, examples/eyetracking_experiment.py, examples/formatted_text_demo.py, examples/generate_stimuli.py, examples/keypress_demo.py, examples/level_test.py, examples/mouse_demo.py, examples/parse_demo.py, examples/pupillometry_experiment.py, examples/simple_experiment.py, examples/sync_test.py, examples/version_checking.py, examples/vocoded_stimuli.py, expyfun/_experiment_controller.py, expyfun/_eyelink_controller.py, expyfun/_sound_controllers.py, expyfun/_tdt_controller.py, expyfun/_utils.py
See new errors here:
https://travis-ci.org/LABSN/expyfun/jobs/51131108
We'll see if Travis thinks I got them all.
=> FIX: Fix new PEP8 standards

git_flow.rst
@drammock @wronk please have a look and see if this makes sense.
=> ENH: Add flow

appveyor.yml, expyfun/_utils.py, expyfun/analyze/_analyze.py, expyfun/analyze/tests/test_analyze_functions.py, make/install_python.ps1
Simple enhancement to allow > 2D arrays for dprime calculation (along last axis).
=> ENH: Allow larger arrays

expyfun/_sound_controllers.py
@lkishline can you try this branch and see if it works for you?
=> FIX: Fix for new Pyglet

examples/keypress_demo.py, expyfun/_experiment_controller.py, expyfun/_input_controllers.py, expyfun/_tdt_controller.py, expyfun/_utils.py, expyfun/stimuli/_hrtf.py
Ready for review/merge @rkmaddox @drammock
=> ENH: Add Cedrus box

git_flow.rst
Looking for feedback on content - will go work on fixing formatting issues now.
=> Adding Debug/bisect

doc/source/whats_new.rst
Replaces #194 and #237, because apparently I forgot everything I used to know about how git works.
Closes #191.
=> What's really new

doc/source/expyfun.rst
as requested by @Eric89GXL in #238
=> add reference to whats new in doc root

.travis.yml, appveyor.yml, expyfun/_experiment_controller.py
=> FIX: Update Travis

expyfun/analyze/_viz.py
I've been using this code for many months (I used this branch when doing the recent JASA plots) so I think it's pretty safe, but I want to double-check that the tests are adequate before giving the go-ahead for merge.  Feel free to review the code changes now though.
=> WIP: Barplot enhancements

README.rst
Ready for review/merge @rkmaddox.
Note I have moved our docs to github-pages @rkmaddox @drammock
=> FIX: Update readme

README.rst, expyfun/_tdt_controller.py, expyfun/tests/test_experiment_controller.py
Addresses #234. Warn if TDT controller is in dummy mode.
=> TDTPy warning

.travis.yml, expyfun/_experiment_controller.py, expyfun/analyze/_viz.py, expyfun/tests/test_ascii.py, expyfun/tests/test_experiment_controller.py, expyfun/tests/test_logging.py
Whoops! Our coverage reports have been a little bit behind...
=> FIX: Fix coverage

expyfun/_input_controllers.py, expyfun/_utils.py, expyfun/tests/test_experiment_controller.py, expyfun/tests/test_eyelink_controller.py, expyfun/visual/_visual.py, expyfun/visual/tests/test_visuals.py
Closes #251.
@drammock @rkmaddox @lkishline can you try this branch to see if you get better results?
=> ENH: Use GLSL pipeline for efficient draws

expyfun/_experiment_controller.py, expyfun/io/tests/test_parse.py, expyfun/tests/test_experiment_controller.py, expyfun/tests/test_eyelink_controller.py, expyfun/tests/test_logging.py, expyfun/tests/test_version.py, expyfun/visual/tests/test_visuals.py
also adds initial flip to end of EC init.  Closes #257, closes #253
=> ENH, FIX: adds mandatory version string argument to EC

examples/experiments/drawing_methods.py, expyfun/tests/test_experiment_controller.py, expyfun/visual/_visual.py
Closes #259.
@drammock see if it works okay for you, if so feel free to merge
=> FIX: Fix background color

.travis.yml
I suspect this might fix Travis.
=> FIX: Fix Travis

expyfun/_git.py, expyfun/tests/test_version.py, setup.py
tested locally, passes nose.  Ready for merge as far as I'm concerned...  @Eric89GXL  @rkmaddox are you cool with this?
=> ENH: allows download_version from expyfun forks

expyfun/_experiment_controller.py, expyfun/_utils.py
Exposes audio type publicly, and also fixes `wait_until`.
=> MRG: Expose audio type

.gitignore, appveyor.yml, expyfun/_git.py, expyfun/_tdt_controller.py, expyfun/tests/test_experiment_controller.py
@drammock can you have a look and see if you think this would have led to a more informative error, instead of silent dummy mode?
=> MRG: Safer dummy mode-ing

expyfun/visual/_visual.py
=> fix: windows GL error message handling

.gitignore, doc/conf.py
=> FIX: Fix title

.travis.yml, expyfun/_experiment_controller.py, expyfun/_sound_controllers.py, expyfun/_utils.py, expyfun/analyze/_analyze.py, expyfun/analyze/tests/test_analyze_functions.py, expyfun/analyze/tests/test_viz.py, expyfun/io/tests/test_parse.py, expyfun/stimuli/__init__.py, expyfun/stimuli/_mls.py, expyfun/stimuli/tests/test_stimuli.py, expyfun/tests/test_eyelink_controller.py, expyfun/tests/test_logging.py, expyfun/tests/test_parallel.py, expyfun/tests/test_version.py, expyfun/visual/tests/test_visuals.py, setup.cfg
I've been meaning to add RT calculation to `press_times_to_hmfc` for a long time and finally got around to it. WIP because I want to see if I can get the OSX CI working.
=> MRG: Add RT calculation

doc/python_reference.rst, examples/stimuli/plot_texture_stimuli.py, expyfun/stimuli/__init__.py, expyfun/stimuli/_stimuli.py, expyfun/stimuli/_texture.py, expyfun/stimuli/tests/test_stimuli.py
This adds support for temporal coherence textures. WIP because I need to add tests.
=> MRG: Textures

doc/conf.py, examples/plot_generate_simple_stimuli.py, examples/plot_simple_experiment.py, expyfun/stimuli/_tracker.py
Closes #297.
@drammock ready for review/merge.
Changes relevant to #297 are in `examples/plot_simple_experiment.py`. I also put in some minor doc fixes to make Sphinx happy since I was checking doc outputs.
=> FIX: Fix simple_experiment

expyfun/stimuli/_texture.py
I am generating a ton of these stimuli, and don't need to hear over and over that they are 1.45 ERB apart.
=> MRG: manage texture verbosity

expyfun/stimuli/_tracker.py
Upon closer inspection, it looks like TrackerBinom isn't actually doing what we said it was doing. This PR is just to make the docs make sense.
=> MRG: Small change to TrackerBinom docs

examples/stimuli/tracker_staircase.py, expyfun/stimuli/_tracker.py, expyfun/stimuli/tests/test_tracker.py
PR to address issues with tracker hitting floors or ceilings. Currently uses ``repeat_limit`` parameter to determine whether to count as ``reversals`` or ``ignore``.
=> MRG: Tracker behavior at floor/ceiling

examples/stimuli/crm_stimuli.py, expyfun/_input_controllers.py, expyfun/_parallel.py, expyfun/_utils.py, expyfun/stimuli/__init__.py, expyfun/stimuli/_crm.py, expyfun/stimuli/_hrtf.py, expyfun/stimuli/_stimuli.py, expyfun/stimuli/tests/test_stimuli.py
Adds functionality for preparing a CRM corpus at a certain sampling rate, and then provides methods for using it, either loading files from hard drive one by one, or by loading all sounds into memory first for fast access.
Continues #247.
Still need to add tests, but would like comments on what is there so far.
=> MRG: CRM Corpus module (part 2)

examples/experiments/progress_bar.py, expyfun/visual/__init__.py, expyfun/visual/_visual.py, expyfun/visual/tests/test_visuals.py
``ProgressBar`` is a class to add to ``expyfun.visual`` that lets you display and update a progress bar during an experiment. I've been using it to let subjects know how far they are in an experiment during breaks between trials.
=> MRG: ProgressBar

expyfun/_experiment_controller.py, expyfun/io/_parse.py, expyfun/io/tests/test_parse.py, expyfun/tests/test_logging.py, setup.cfg
Ready for review/merge from my end.
@maddycapp27 can you look to see if you agree this would be useful?
=> MRG: Save and report the version

expyfun/visual/_visual.py, expyfun/visual/tests/test_visuals.py
A feature requested by @mfreilly.
@drammock ready for review/merge from my end.
=> MRG: Allow grayscale images

.travis.yml, circle.yml, doc/Makefile, doc/conf.py, expyfun/_experiment_controller.py, expyfun/_tdt_controller.py, expyfun/_utils.py
This should hopefully fix the flushing bug I've been hitting.
@drammock do you have time to look to see if this makes sense to you?
=> FIX: Fix flushing

expyfun/analyze/_analyze.py, expyfun/analyze/tests/test_analyze_functions.py
Adds bias measure to d' calculations.
Ready for review/merge from my end.
=> MRG: Add bias

doc/python_reference.rst, expyfun/__init__.py, expyfun/_experiment_controller.py, expyfun/_sound_controllers.py, expyfun/_trigger_controllers.py, expyfun/tests/test_experiment_controller.py
@mfreilly can you try this branch on the experimental computer that will run the auditory paradigm? Once it appears to work, we should probably verify that the timing accuracy (jitter and delay) with an oscilloscope.
=> FIX: Reenable parallel port triggering

expyfun/_utils.py, expyfun/io/_parse.py
=> MRG: Minor fixes

examples/analysis/analysis_demo.py, expyfun/analyze/__init__.py, expyfun/analyze/_analyze.py, expyfun/analyze/_viz.py, expyfun/analyze/tests/test_analyze_functions.py
=> MRG: fix dprime_2afc

expyfun/_experiment_controller.py, expyfun/tests/test_experiment_controller.py
This is a function to let participants type responses (and view those responses as they type).
To do:
handling of special characters (like 'space', punctuation)
blinking cursor?
tests
To debate:
How to exit input? ``stop_key`` parameter v. a submit button to click (former is easier for participant, but more prone to prematurely exiting)
Recording response -- is logging by ``ec.screen_text()`` sufficient? annoying? Should the function return the final string?
=> MRG: Text input

expyfun/_experiment_controller.py
I forgot to make sure the logging actually happened! Also fixed the docs.
=> FIX: Logging for Text Input

.travis.yml, Makefile, doc/conf.py, examples/experiments/tracker_dealer.py, examples/experiments/tracker_dealer_doublesided.py, expyfun/_utils.py, expyfun/analyze/_analyze.py, expyfun/codeblocks/_pupillometry.py, expyfun/io/_parse.py, expyfun/stimuli/_crm.py, expyfun/stimuli/tests/test_stimuli.py, ignore_words.txt
The ultimate pedantic PR.
But really I just want to see if someone other than @maddycapp27 opening a PR will trigger CircleCI.
=> MRG: Check spelling

expyfun/_experiment_controller.py, expyfun/tests/test_experiment_controller.py
This alters ``ec.text_input()`` such that brief instructions can be given and so that the cursor appears before the participant begins typing.
=> MRG: Text input more user friendly

expyfun/stimuli/_tracker.py
Currently just here to fix the lack of ValueErrors for ``up`` and ``down`` in ``TrackerBinom``
=> FIX: Tracker issues

.circleci/config.yml, .gitignore, .travis.yml, Makefile, appveyor.yml, conftest.py, expyfun/_experiment_controller.py, expyfun/_utils.py, expyfun/analyze/tests/test_analyze_functions.py, expyfun/analyze/tests/test_viz.py, expyfun/io/tests/test_parse.py, expyfun/io/tests/test_wav.py, expyfun/stimuli/_crm.py, expyfun/stimuli/tests/test_mls.py, expyfun/stimuli/tests/test_stimuli.py, expyfun/stimuli/tests/test_tracker.py, expyfun/tests/test_experiment_controller.py, expyfun/tests/test_eyelink_controller.py, expyfun/tests/test_logging.py, expyfun/tests/test_parallel.py, expyfun/tests/test_trigger_conversion.py, expyfun/tests/test_utils.py, expyfun/tests/test_version.py, expyfun/visual/_visual.py, expyfun/visual/tests/test_visuals.py, setup.cfg
Long-overdue migration to `pytest` syntax.
Also bumps Travis to 3.7.
=> ENH: Move to pytest syntax

expyfun/analyze/tests/test_analyze_functions.py, expyfun/visual/_visual.py, expyfun/visual/tests/test_visuals.py
should probably add a test before merging.  Also fixes an incorrect docstring in `RawImage.bounds`
=> add RawImage.get_rect

.gitignore, .travis.yml, MANIFEST.in, Makefile, setup.py
Missed adding a module to `setup.py` in #366, prevent that in the future. Also check our MANIFEST.in.
=> ENH: Check manifest

expyfun/tests/test_experiment_controller.py
Just a small fix for `contextmanager` use.
=> FIX: contextmanager

doc/rtmixer_installation.rst, expyfun/_experiment_controller.py
=> FIX: fix typo

doc/rtmixer_installation.rst
=> DOC: Unnecessary portaudio

doc/python_reference.rst, examples/stimuli/tracker_staircase_MHW.py, expyfun/io/_parse.py, expyfun/stimuli/__init__.py, expyfun/stimuli/_tracker.py, expyfun/stimuli/tests/test_tracker.py
Adding the MWH tracker to the trackers, which is what audiometers use.
=> MRG: Add modified Hughson-Westlake tracker

expyfun/_experiment_controller.py, expyfun/visual/_visual.py
This workaround is 5 years old, hopefully we can get rid of it now.
Also adds a bit of maybe useful debugging information.
=> MAINT: Remove workaround

.travis.yml, appveyor.yml, azure-pipelines.yml, setup.cfg
Let's see what happens on Pyglet master. Probably a failure due to OpenGL version. Maybe I'll need to recompile Mesa, or see if the Pyglet folks can use 3.0 instead of 3.3 (or whatever)...
=> FIX: Try again

.travis.yml, doc/getting_started.rst, expyfun/_experiment_controller.py, expyfun/io/_parse.py, expyfun/io/tests/test_parse.py, expyfun/stimuli/_texture.py, expyfun/stimuli/_tracker.py, expyfun/tests/test_experiment_controller.py, expyfun/visual/tests/test_visuals.py, setup.cfg, setup.py
Needed for some of @ktavabi's files
=> ENH: Allow parsing old files

doc/getting_started.rst
=> fix install command

examples/sync/sync_test.py, expyfun/_sound_controllers/_rtmixer.py, expyfun/io/tests/test_parse.py
Closes #429
I haven't tested this code locally because I need to set up a Spyder env. @rkmaddox @bonniekwlau feel free to try it in the meantime to see if it fixes your problem.
=> ENH: Allow close-reopen cycles to work (maybe!)

expyfun/_sound_controllers/_rtmixer.py
It might be helpful to list valid options to guide new users in getting expyfun set up.
=> If sound card API not found, list options

.circleci/config.yml, azure-pipelines.yml, doc/conf.py, doc/getting_started.rst, expyfun/_experiment_controller.py, expyfun/_eyelink_controller.py, expyfun/_utils.py, expyfun/stimuli/tests/test_stimuli.py, expyfun/tests/test_experiment_controller.py, setup.cfg
=> update install docs; silence doc build warning

azure-pipelines.yml, expyfun/tests/test_experiment_controller.py, setup.cfg
Test for https://github.com/pyglet/pyglet/pull/528. Will update to use `1.5-maintenance` again once that branch is merged
=> CI: Try branch
