LABSN/expyfun

- expyfun/codeblocks/_pupillometry.py
Allows counterbalancing across subjects, so that (for example) half of them have steady tone as targets and half have FM as targets.  Needed to address reviewer comments.
This should be good to go (and passes nose tests in dummy mode) but I'm marking as WIP until I've run through both flag options while connected to the EyeLink.
> MRG: adds flag to swap tone/targ stims in pupil tone impulse response codeblock

- examples/experiments/sync_test.py
- expyfun/analyze/tests/test_viz.py
Moves text to side and makes an empty white circle in the middle so that the photodiode timing can be referenced exactly to the center of the screen.
> MRG: add circle

- .travis.yml
- examples/stimuli/video_playback.py
- expyfun/_experiment_controller.py
- expyfun/tests/test_experiment_controller.py
- expyfun/visual/__init__.py
- expyfun/visual/_visual.py
- expyfun/visual/tests/test_visuals.py
This PR is a (hopefully) improved implementation of pyglet video playback.  The PRs for the other two attempts have been closed without merging.  It also changes the behavior of `ec.call_on_next_flip` and `ec.call_on_every_flip` by removing the internal call to `functools.partial` (see #269); henceforth, users must call `partial` (as needed) before adding functions to the on_next / on_every queue.  This has the advantage of allowing functions in the queue to be easily detected (via `ec.on_every_flip_functions.index()` and subsequently `pop()`ped.
The attempts at running travis with `trusty` caused pip to choke on mne, so I'm reverting to `precise` and avoiding the wget error via `--no-check-certificate`.
Closes #267 
Closes #269
> MRG: New video implementation

- .gitignore
- examples/experiments/keyrelease_demo.py
- expyfun/_experiment_controller.py
- expyfun/_input_controllers.py
- expyfun/_sound_controllers.py
- expyfun/_tdt_controller.py
- expyfun/_version.py
- expyfun/tests/test_experiment_controller.py
Collecting key-release events
~~I've added a `get_releases()` method on `ExperimentController` to be able to get key release events.~~
~~There's room for refactoring as I've just duplicated most of the keypress code.~~
~~I haven't been able to run/ adapt the tests properly since nosetest in a virtualenv uses global packages and I get the _check_pyglet error.~~ *resolved this with http://stackoverflow.com/a/864967* 
I have added an example script.
Summary of todo's:
> [ENH] Keyboard key releases.

- expyfun/_experiment_controller.py
- expyfun/_sound_controllers.py
@bonniekwlau can you try this branch and see if it makes the experiment work on your OSX machine?
OSX is refuses to hide a fullscreen window, so this makes our hide/show deal with fullscreen-ness.
> MRG: Minor fixes for OSX

- expyfun/_git.py
- expyfun/_version.py
- expyfun/tests/test_version.py
- setup.py
@drammock on OSX setting the `env` during `setup.py` can break things because it makes `git` no longer available. I think you set at least some of this up -- think it's reasonable?
Closes #271.
Closes #305.
> MRG: Dont mangle env during setup

- expyfun/_eyelink_controller.py
(copied from issue description) After setting up the eyelink I noticed that there was a discrepancy between coordinate systems.
`el.get_eye_position()` returns location in pixels with the center of the screen being `[0, 0]`. The eyelink itself claims to output a location where the top left is `[0, 0]` (but it seems more like it's using the bottom left). `ec._convert_units()`, however, assumes that the pixel locations use the bottom left of the screen as `[0, 0]`.
Since `el.wait_for_fix()` uses both `el.get_eye_position()` and `ec._convert_units()`, the coordinates never match up.
> WIP: Eyelink origin discrepancy

- expyfun/_git.py
- expyfun/_utils.py
- expyfun/tests/test_version.py
- setup.py
Our current version code returns junk like `.dev0+c` so version assertion round-trips fail. This fixes the problem (there was a lingering `[0]` in `setup.py`)
> MRG: Fix version

- expyfun/stimuli/_tracker.py
- expyfun/stimuli/tests/test_tracker.py
Issue with tracker stopping at ``stop_trials + 1`` or ``stop_reversals + 1`` rather than at the actual stopping criteria.
> MRG: Fix tracker stopping

- expyfun/_eyelink_controller.py
We have not been able to use the right eye for any tracking until I found what looks to be missing parentheses.
Is this just a fix for us?
> FIX: Eyelink not able to get position for right eye

- expyfun/_eyelink_controller.py
- expyfun/tests/test_eyelink_controller.py
We ran into issues with the HV5 calibration scheme for the eyetracker and wanted to test out some other options (HV9 and H3 so far). 
I'd also like to add HV13 if possible but am not sure what those target coordinates actually are--based on the icon in the eyelink settings window they aren't quite an even grid and I'm still trying to figure those numbers out.
Disclaimer: I'm working on the computer that's actually attached to the eyelink system so all commits will come from rkmaddox for this PR but they are from me. My apologies!
> MRG: Add calibration schemes to eyetracker

- expyfun/_experiment_controller.py
Previously, on `__exit__` we were effectively doing `fid.close()` then nothing (though we wanted to do `fid.flush()`), this corrects the order to be `fid.flush()` followed by `fid.close()`.
@drammock can you double-check the logic?
No test to update because this doesn't have an obvious deterministic effect AFAIK. But I'm hoping it might solve #327, where some lines seem to be missing in the `.tab` file. But either way this can be merged as a bugfix.
> FIX: Flush then close

- expyfun/_experiment_controller.py
- expyfun/tests/test_experiment_controller.py
This just adds a few extra lines in ``ec.screen_prompt`` to allow for subjects to click to advance rather than press a key
> MRG: advance from screen_prompt with click

- .gitignore
- Makefile
- expyfun/_experiment_controller.py
- expyfun/io/_parse.py
- expyfun/stimuli/_crm.py
- expyfun/stimuli/_tracker.py
- expyfun/tests/test_experiment_controller.py
- expyfun/visual/_visual.py
@rkmaddox @maddycapp27 because trackers are identified by their memory location, it is actually possible for tracker names to repeat in the unlucky case where the same memory address is used by multiple trackers (e.g., one is instantiated after another is garbage collected). I hit such a use case recently. This fixes the reconstruction.
Should we also fix the naming, e.g. by also tagging with the time of instantiation (to the millisecond), too?
> FIX: Fix recon

- examples/sync/sync_test.py
- expyfun/_experiment_controller.py
- expyfun/tests/test_experiment_controller.py
The procedure to test in case someone is curious, only on Windows (for now):
1. On `master`, run `sync_test.py` with `response_device='keyboard'`:
1. Press any key (like space) and notice the flashing speeds up (because it does not wait the 0.5 sec.) 
2. Press alt-tab to switch to any other process
3. Press any key (like space) and notice the flashing does not change, and pressing "ctrl" does not close the window.
4. Click in the expyfun window
5. Press "ctrl" to close the window (it closes).
2. On this branch, repeat the above, but steps (iv) is not necessary to get step (v) behavior -- it happens already on step (iii) (i.e., focus is regained automatically).
> ENH: Refocus on Windows

- examples/sync/sync_test.py
- expyfun/_experiment_controller.py
This could be useful e.g. to test video playback smoothness on testing machines.
Closes #356.
> MRG: Add unsafe flipping mode

- expyfun/codeblocks/_pupillometry.py
At some point pyeparse __init__ used to include a line `Raw = RawEDF` (introduced in [this commit](https://github.com/pyeparse/pyeparse/commit/c7f61e84dbad49163fbd3fade103ebf0db700330#diff-51ad22576f4f2ea6d270fed13a3badd3R7) but not sure when it was removed). Anyway, since it was removed the creation of a graph at the end of the pupillometry code block no longer works. This one-liner fixes it.
> fix: class 'Raw' doesn't work with current pyeparse

- expyfun/_experiment_controller.py
pyglet 1.3.2 is complaining when I pass an int `screen_num` to ExperimentController (or when I set `SCREEN_NUM` in the machine config).  This fixes that.  Not well tested yet, but have a look.
@larsoner
> WIP: fix pyglet screen num (wants screen instance)

- .travis.yml
- codecov.yml
- expyfun/stimuli/tests/test_stimuli.py
- expyfun/tests/test_logging.py
Should get CIs green and allow us to wait on dropping 2.7 support a bit longer if we want.
> MAINT: Decorate mne tests

- doc/conf.py
- doc/getting_started.rst
- doc/parallel_installation.rst
- doc/rtmixer_installation.rst
- examples/sync/sync_test.py
- expyfun/__init__.py
- expyfun/_experiment_controller.py
- expyfun/_fixes.py
- expyfun/_sound_controllers/__init__.py
- expyfun/_sound_controllers/_pyglet.py
- expyfun/_sound_controllers/_rtmixer.py
- expyfun/_sound_controllers/_sound_controller.py
- expyfun/_tdt_controller.py
- expyfun/_trigger_controllers.py
- expyfun/_utils.py
- expyfun/conftest.py
- expyfun/stimuli/_hrtf.py
- expyfun/stimuli/_mls.py
- expyfun/stimuli/_texture.py
- expyfun/stimuli/tests/test_tracker.py
- expyfun/tests/test_experiment_controller.py
- expyfun/tests/test_logging.py
- expyfun/tests/test_utils.py
Haven't tested the multichannel stuff or fixed delay on this branch, but in theory it should work since fixed delay seemed to work with what is now `SOUND_CARD_FIXED_DELAY` added to the time. For my built in sound card on Linux, 10ms (`0.01`) is enough.
@rkmaddox if you are bored feel free to try it, but it might need a bit of work still since I haven't re-tested with a scope or tried my multichannel card, but at least with my `pulse` ALSA "card" (with 32 outputs for some reason) this works in `sync_test.py`:
```
with ExperimentController('SyncTest', full_screen=True, noise_db=-np.inf,
participant='s', session='0', output_dir=None,
suppress_resamp=True, check_rms=None,
version='dev', n_channels=8) as ec:
ec.load_buffer(np.tile(np.r_[0.1, np.zeros(99)][np.newaxis], (8, 1)))  # RMS == 0.01 …
```
> MRG: Add multi-channel support, fixed delay

- .circleci/artifact_path
Should enable a [little GitHub app](https://github.com/apps/circleci-artifacts-redirector) that [I made](https://github.com/larsoner/circleci-artifacts-redirector) to give a quicker link to the built docs.
> ENH: Add CirclecI redirection

- .circleci/config.yml
Use the standard (MNE, SciPy) name for the doc build CircleCI job.
> MAINT: Use standard name

- doc/rtmixer_installation.rst
Closes #390
Current lines in rtmixer_installation.rst read:
```
$ sudo apt install libportaudio2  # only if on Linux!
$ brew install portaudio  # only if on OSX!
$ pip install sounddevice
$ python -m sounddevice  # just to see if it worked
$ git clone git://github.com/spatialaudio/python-rtmixer
$ cd python-rtmixer
$ git submodule update --init
$ pip install -e .
```
Can't find `portaudio` headers
Added a line which worked (instructions came from https://github.com/spatialaudio/python-rtmixer):
```
$ sudo apt install libportaudio2  # only if on Linux!
$ brew install portaudio  # only if on OSX!
$ pip install sounddevice
$ python -m sounddevice  # just to see if it worked
$ git clone git://github.com/spatialaudio/python-rtmixer
$ cd python-rtmixer
$ git submodule update --init
$ pip …
```
> MRG: adding extra line for rtmixer installation instructions for linux

- expyfun/_sound_controllers/_pyglet.py
- expyfun/_sound_controllers/_rtmixer.py
- expyfun/_sound_controllers/_sound_controller.py
I don't love this fix/workaround but if there is something fishy with the stream time provided by the RME ASIO drivers, this should make sure we don't inadvertently cut off triggers.
Also removes a `mixer.start_time = mixer.time` assignment that is just leftover cruft.
> FIX: Missing triggers

- expyfun/analyze/_analyze.py
- expyfun/analyze/tests/test_viz.py
- setup.cfg
Having `ion` in the example makes the tests horribly slow, as they cause `ion` to be on when plotting. This should fix it.
> FIX: Don't call ion

- expyfun/_experiment_controller.py
Even when using the same clock 10 µs can be tough with Python overhead. So let's bump our tol up to 50.
cc @maddycapp27 let me know if this works for you. If it does I'll leave open for a bit in case there are other joystick-related fixes we need.
> FIX: Bump up tolerance for drift

- .travis.yml
- doc/getting_started.rst
- doc/python_reference.rst
- examples/sync/sync_test.py
- expyfun/__init__.py
- expyfun/_experiment_controller.py
- expyfun/_utils.py
- expyfun/tests/test_experiment_controller.py
- setup.cfg
Adding:
```
"SCREEN_SIZE_PIX": "1920,1200",
```
now ensures that the fullscreen window obtained is this resolution. If I set it to something else (e.g., `800,800`) I get an error message:
```
RuntimeError: Requested window size [800 600] but got size (1920, 1200), is the resolution set incorrectly?
```
Also `sync_test.py` now has a rectangle that is the standard size of a credit card, which hopefully makes it fairly easy to check.(Also you should be able to see if the credit card "looks funny", though you maybe probably see that with the circle.) I've checked and on my screen with proper `expyfun.json` it is indeed the size of a credit card.
@nordme @drammock can you review the code and try it out at least `sync_test.py` on your system(s)?
Closes #404
> MRG, ENH: Check resolution and improve sync_test

- expyfun/_experiment_controller.py
- expyfun/visual/_visual.py
1. Removes `_legacy_setup`, which we shouldn't need because it was for old Windows (like Windows 2000) and no longer exists in Pyglet as of Sept 2019.
2. Adds a workaround for text bugs.
For (2), on `master` this code:
```
from expyfun import ExperimentController
with ExperimentController(
exp_name='CRM corpus example', window_size=(720, 480),
full_screen=False, participant='foo', session='foo', version='dev',
output_dir=None) as ec:
ec.screen_prompt('Report the color and number spoken by the female '
'talker.', wrap=True, live_keys=['1'])
```
Produces:
And on this PR:
> MRG, FIX: Legacy and wrap

- .travis.yml
- expyfun/_experiment_controller.py
- expyfun/_sound_controllers/_rtmixer.py
- expyfun/_utils.py
- expyfun/tests/test_experiment_controller.py
@JustinTFleming can you try adding this to your script after EC initialization:
```
ec.set_stim_db(60.)  # assuming you have stim_rms=0.01, the default value
assert ec._stim_scaler == 1.
```
and then see if 1) stimuli load faster than 7 sec, and 2) that they still sound correct? The assertion is necessary to make sure we avoid a scaling later.
This PR should eliminate all copies except the last one (concatenating the sound and the trigger values), there triggering a copy which would be difficult to avoid (we would have to tell `rtmixer` to play two sounds at the same time and hope it did so correctly, which is dicey).
If this ends up being the bottleneck, we could make a new triggering mode where you have to supply the sound stimulus *with the trigger channels zeroed out* (e.g., for 6 …
> MRG, ENH: Speed up buffering

- examples/stimuli/advanced_video.py
- examples/stimuli/simple_video.py
- expyfun/_experiment_controller.py
- expyfun/_eyelink_controller.py
- expyfun/tests/test_experiment_controller.py
- expyfun/visual/_visual.py
> BUG: Fix video playback with other visuals

- .travis.yml
- examples/experiments/mouse.py
- expyfun/_experiment_controller.py
- expyfun/_input_controllers.py
- expyfun/_tdt_controller.py
- expyfun/tests/test_experiment_controller.py
Tested on Linux and macOS, Windows in progress. @drammock feel free to review and if you're happy I'll merge once it works on Windows.
cc @LiesbethGijbels this will allow you just to use `ec.move_mouse_to((0, 0))` instead of using `pyautogui`.
> MRG, ENH: Add move_mouse_to

- .circleci/config.yml
- .travis.yml
- appveyor.yml
- azure-pipelines.yml
- expyfun/_experiment_controller.py
- expyfun/_sound_controllers/_sound_controller.py
- expyfun/_tdt_controller.py
- expyfun/_trigger_controllers.py
- expyfun/_utils.py
1. Add `SOUND_CARD_TRIGGER_ID_AFTER_ONSET` config var to allow stamping the TTL IDs after the 1 trigger so that a single sound can be played. Should help with rtmixer/portaudio fragility when sounds are stopped and started in close proximity.
2. Change `stamp_triggers` for the sound controller to return as quickly as possible when `wait_for_last=False`. We had made it wait until all but the last trigger was stamped to be consistent with TDT and parallel triggers. It seems better not to do this if we don't need to -- it decreases the uniformity of our approach across platforms, but makes the sound card platform (probably the way of the future) work better.
3. Fix `wait_secs` when not used in an `ec` context. Probably doesn't matter but I noticed this bug was introduced in #399.
> ENH: Allow triggering after onset

- azure-pipelines.yml
- examples/stimuli/advanced_video.py
- examples/stimuli/simple_video.py
- expyfun/_experiment_controller.py
- expyfun/analyze/tests/test_analyze_functions.py
- expyfun/analyze/tests/test_viz.py
- expyfun/tests/test_docstring_parameters.py
- expyfun/tests/test_experiment_controller.py
- expyfun/tests/test_version.py
- expyfun/visual/_visual.py
- expyfun/visual/tests/test_visuals.py
- setup.cfg
@drammock looking at Azure logs like this I don't see any skips because of missing `ffmpeg`, which suggests that things work there:
https://dev.azure.com/LABSN/expyfun/_build/results?buildId=328&view=logs&jobId=db093384-e8eb-5bcc-f0a9-2a8f5e4220af&j=db093384-e8eb-5bcc-f0a9-2a8f5e4220af&t=b83569e5-86aa-5f40-c5f2-cb2c66a2c238
This PR explicitly adds a test that the video example runs. On my Linux machine, it pops up, the video plays, and then it exits. The same should in principle happen on Windows. Let's see...
If it does, @drammock feel free to play with your local setup / deps until it works, too, and push to this PR to update any instructions.
Closes #436
> CI: Test video explicitly

- examples/stimuli/simple_video.py
- expyfun/_experiment_controller.py
- expyfun/visual/_visual.py
We had two problems, I think:
1. We need to call `pyglet.clock.tick(poll=True)` to get the video to advance, and 
2. The alpha for the video is messed up on Windows
(2) has been opened upstream as a Pyglet bug (https://github.com/pyglet/pyglet/issues/531), but the workaround here should be fine.
@JustinTFleming can you test it with latest pyglet (1.5.21) and pyglet-ffmpeg?
FWIW @drammock for me when I play the video it plays way too fast on Linux -- it should take ~6 sec but it takes ~1. But this seems to be the case with newer Pyglet even before these PRs. Do you want to take a look? IIRC you worked on the timing stuff originally...?
> BUG: Fix video on Windows for Pyglet > 1.3

- expyfun/visual/_visual.py
@JustinTFleming this should address https://github.com/LABSN/expyfun/pull/439#issuecomment-1013295729 by explicitly trying to use `FFmpegDecoder`
> ENH: Prefer FFmpegDecoder for video

- .gitignore
- doc/getting_started.rst
- environment_test.yml
Mainly this PR adds recommendations in _getting\_started.rst_ to install a version of pyglet that works with the current expyfun codebase. I was unable to create a browser-friendly version of the document (i.e. via the `make` command), so I'm uncertain if the formatting is correct.  Also, for the current version of the document, as rendered in my brower, I see text like ":func:\`expyfun.get_config_path\`", which I think are broken links.  I'd be happy to make fixes with some guidance.
I also made minor additions to the _requirements\_test.yml_ and _.gitignore_ files.
> Doc updates addressing #431

- expyfun/_experiment_controller.py
- expyfun/_version.py
- expyfun/visual/_visual.py
- expyfun/visual/tests/test_visuals.py
- only works using sound card with Pyglet backend.
- API is `ec.video.play(audio=True)` (default False for backcompat).
> allow playing audio stream from videos
